##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/rbtxjlmy/public_html/
    - /bin/cp -r /home2/rbtxjlmy/repositories/cbx-vite/cbx/dist/* $DEPLOYPATH
